### ISSUE TITLE
충돌 감지 최적화 시스템

### ISSUE THREAD

**Issue by dldyou** [dldyou2/Brick_Breaker#7]
벽돌(좀비)가 나오는 구간은 **5줄**로 결정되어 있다. 따라서 현재 공의 위치에서 충돌 감지를 해야만 하는지를 파악하면 연산을 많이 줄일 수 있을 것이다. 또한, 충돌은 한 번에 하나씩 일어난다는 점을 이용하여 아래와 같은 최적화 시스템을 구축할 수 있을 것이다.

충돌이 일어날 수 있는 줄만 확인하는 시스템을 구출할 수 있다.
1. 공의 $y$좌표가 몇 번째 줄에 해당하는지를 확인한다. 
1-1. 어떤 줄에도 해당하지 않는 경우: 좀비와의 충돌은 검사를 하지 않아도 된다.
1-2. $i$번째 줄에 해당하는 경우: 그 줄에서 가장 앞의 좀비보다 공의 $x$좌표가 작다면 나머지 검사는 필요 없다. 만약 아닌 경우는 해당 줄의 좀비들과의 충돌을 검사하다가 충돌이 된 경우 즉시 나머지 충돌 검사는 종료한다. 

식물이 발사하는 투사체에 대해서는 가장 앞의 좀비만 확인하면 되니 식물의 투사체 개수만큼만 연산을 진행하면 된다.

**Comment by dldyou2** [comment]
가장 앞의 좀비만 확인하는 경우 생길 문제점이 있습니다. 
- 좀비가 지나간 후에 해당 자리에 식물을 설치하는 경우
- 따라서 결국 해당 줄의 좀비와 모두 비교를 해야 합니다.
